import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Usama Imdad's Resume",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div style={{marginBottom:"10px", padding: "10px", textAlign:"center"}} className="nav-bar">
          <Link href="/">HOME</Link> | <Link href="/projects">PROJECTS</Link> | <Link href="/resume">RESUME</Link> | <Link href="/about">ABOUT ME</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
